# TeStore插件仓库依赖此Action从jsDelivr获取CDN加速API数据，切勿删改！

name: "推送后自动更新数据标签"

on:
  push:
    branches:
      - "master"

jobs:

  api-tag:
    name: "更新以API数据命名的Tag"
    runs-on: "ubuntu-latest"

    steps:
      - name: "检出当前Git仓库数据"
        uses: actions/checkout@v2
        run: |
          git fetch --prune --unshallow --tags

      - name: "获取最新发布Tag名"
        id: "get-tag"
        run: |
          tag=`git describe --abbrev=0 --tags`
          echo "::set-output name=tagName::$tag"

      - name: "删除上一次发布Tag"
        uses: dev-drprasad/delete-tag-and-release@v0.1.2
        with:
          delete_release: true
          tag_name: ${{ steps.get-tag.outputs.tagName }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "获取ZIP_CDN文件数"
        id: "get-total"
        working-directory: ZIP_CDN
        run: |
          count=`git ls-files | wc -l`
          echo "::set-output name=toTal::$count"

      - name: "获取最后提交时间戳"
        id: "get-update"
        run: |
          stamp=`git log -1 --pretty=format:%ct`
          echo "::set-output name=upDate::$stamp"

      - name: "发布新实时打包Tag"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.get-total.outputs.toTal }}-${{ steps.get-update.outputs.upDate }}"
          prerelease: true
          title: "实时打包标签(自动生成请忽略)"
